<?php
require_once __DIR__ . '/../includes/config.php';
require_once __DIR__ . '/../includes/functions.php';

$slides = array(
    array(
        'title' => 'EKO FM 91.2',
        'subtitle' => 'The Voice of Karamoja',
        'line' => 'Licensed Commercial Radio Station',
        'badge' => 'Since 2014',
        'copy' => 'EKO FM is a privately owned commercial radio station located in Kotido Municipality, Karamoja Region. Fully licensed by the Uganda Communications Commission (UCC), the station serves communities with reliable information, entertainment, and impactful programming.',
        'button_primary_text' => 'Listen Live',
        'button_primary_link' => '#',
        'button_secondary_text' => 'Contact Us',
        'button_secondary_link' => '#',
        'caption' => 'Booma Ground Road, Kotido',
        'foot' => 'Tel: +256 393 242 726 | Email: ekofmkotido@gmail.com',
        'card_opacity' => 64,
        'card_position' => 'left',
    ),
    array(
        'title' => 'Wide Regional Coverage',
        'subtitle' => 'Reaching Communities Across Karamoja',
        'line' => '300KM Broadcast Radius',
        'badge' => '1KW Digital Transmitter',
        'copy' => 'EKO FM operates with a powerful 1KW crown digital transmitter and 6-bay antennas, enabling coverage across Kotido, Kaabong, Napak, Abim, Moroto, Agago, Otuke, and parts of Kitgum, Amuria, Pader, Alebtong, and Western Kenya.',
        'button_primary_text' => 'Advertise With Us',
        'button_primary_link' => '#',
        'button_secondary_text' => 'View Map',
        'button_secondary_link' => '#',
        'caption' => 'Strong signal. Wider reach.',
        'foot' => 'Connecting urban and rural audiences',
        'card_opacity' => 64,
        'card_position' => 'left',
    ),
    array(
        'title' => 'Diverse Radio Programs',
        'subtitle' => 'Serving Every Listener',
        'line' => 'Community-Centered Content',
        'badge' => 'Inclusive Programming',
        'copy' => 'Our programs target urban and rural audiences including women, youth, farmers, and entrepreneurs. Content covers agriculture, health, education, environment, culture, sports, and economic empowerment.',
        'button_primary_text' => 'View Programs',
        'button_primary_link' => '#',
        'button_secondary_text' => 'Partner With Us',
        'button_secondary_link' => '#',
        'caption' => 'Content that transforms lives',
        'foot' => 'Empowering communities through information',
        'card_opacity' => 64,
        'card_position' => 'left',
    ),
    array(
        'title' => 'Our Aim',
        'subtitle' => 'Transforming Communities Through Media',
        'line' => 'Driven by Impact',
        'badge' => 'Sustainable Growth',
        'copy' => 'EKO FM aims to improve agricultural productivity, food security, and economic development by providing timely and reliable information that empowers communities to utilize their resources effectively.',
        'button_primary_text' => 'Join the Movement',
        'button_primary_link' => '#',
        'button_secondary_text' => 'Learn More',
        'button_secondary_link' => '#',
        'caption' => 'Information that builds futures',
        'foot' => 'From awareness to transformation',
        'card_opacity' => 64,
        'card_position' => 'left',
    ),
    array(
        'title' => 'Advertise With EKO FM',
        'subtitle' => 'Flexible & Affordable Rates',
        'line' => 'Grow Your Brand',
        'badge' => 'Prime & Standard Slots',
        'copy' => 'EKO FM generates revenue through advertisements, sponsored programs, DJ mentions, talk shows, and announcements. Rates vary based on audience reach and time slots, with premium pricing during peak hours.',
        'button_primary_text' => 'View Rate Card',
        'button_primary_link' => '#',
        'button_secondary_text' => 'Book Slot',
        'button_secondary_link' => '#',
        'caption' => 'Maximum reach. Better results.',
        'foot' => 'Custom packages available',
        'card_opacity' => 64,
        'card_position' => 'left',
    ),
);

save_setting('home_hero_slides', json_encode($slides));

echo "Seeded 5 brochure slides";
